/* eslint-disable max-len */
// Generated by dashboard/scripts/create_config/index.ts
export const config: any = {
  gaTrackingId: 'UA-1234568-9',
  aws_project_region: '{{region}}',
  aws_cognito_identity_pool_id: '{{identity_pool_id}}',
  aws_cognito_region: '{{region}}',
  aws_user_pools_id: '{{cognito_user_pool}}',
  aws_user_pools_web_client_id: '{{login_client_id}}',
  aws_appsync_graphqlEndpoint: '{{aws_appsync_graphqlEndpoint}}',
  aws_appsync_region: '{{region}}',
  aws_appsync_authenticationType: 'AWS_IAM',
  Auth: {
    identityPoolId: '{{identity_pool_id}}',
    region: '{{region}}',
    userPoolId: '{{cognito_user_pool}}',
    userPoolWebClientId: '{{login_client_id}}',
  },
};

export default config;
