/* eslint-disable max-len */
// Generated by dashboard/scripts/create_config/index.ts
export const config: any = {
  gaTrackingId: 'UA-1234568-9',
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id:
    'eu-central-1:41789590-ccfc-496d-b38a-495ed57e6a86',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_HV8PCNy1W',
  aws_user_pools_web_client_id: 'o64qme7nlraasfhkjm3qjad9h',
  aws_appsync_graphqlEndpoint:
    'https://m7q2weeuyngehcieuut2aemz54.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_appsync_authenticationType: 'AWS_IAM',
  Auth: {
    identityPoolId: 'eu-central-1:41789590-ccfc-496d-b38a-495ed57e6a86',
    region: 'eu-central-1',
    userPoolId: 'eu-central-1_HV8PCNy1W',
    userPoolWebClientId: 'o64qme7nlraasfhkjm3qjad9h',
  },
};

export default config;
