#!/bin/bash

echo -e "===\n>> Pre-push Hook: Checking branch name ..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|develop)"
COMMIT_MESSAGE=$(git log -1 --pretty=%B)
BRANCH_REGEX="(feat|fix)/[0-9]+*"

# echo -e "\n $1 $2 $3 --"

# if [[ $1 != *"$BRANCH"* ]]
# then
#   echo -e "\n🚫 You must use (git push origin $BRANCH) (git push origin $BRANCH).\n" && exit 1
# fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES && ! "$COMMIT_MESSAGE" == *.. ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and used a PR." && exit 1
fi

if [[ ! "$BRANCH" == $BRANCH_REGEX && ! "$COMMIT_MESSAGE" == *.. ]]
then
  echo -e "\n🚫 Branch name $BRANCH doesn't follow naming convention: $BRANCH_REGEX. See more in wiki!" && exit 1
fi

echo -e ">> Finish checking branch name.\n==="

exit 0